name: Windows

on:
  push:
    branches:
      - main
      # PR branches that alter the build process should be prefixed with `build/`, so
      # that this workflow runs.
      - 'build/**'
  workflow_call:
  workflow_dispatch:

jobs:
  php:
    name: PHP
    uses: ./.github/workflows/php-windows.yml

  app:
    name: App
    runs-on: windows-latest
    needs:
      - php
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Set up Yarn
        run: |
          corepack enable
          yarn set version berry

# Dependency caching is temporarily disabled due to https://github.com/npm/cli/issues/4828.
#      - name: Cache dependencies
#        id: cache
#        uses: actions/cache@v4
#        with:
#          path: node_modules
#          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
#        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Download PHP interpreter
        uses: actions/download-artifact@v4
        with:
          name: php-windows

      - name: Determine latest Composer version
        id: composer-latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: composer/composer
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out latest Composer release
        uses: actions/checkout@v4
        with:
          repository: composer/composer
          ref: ${{ steps.composer-latest.outputs.release }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: './bin/composer'

      - name: Clean up Composer code base
        shell: bash
        run: rm -r -f .git doc phpstan tests
        working-directory: './bin/composer'

      - name: Create application bundle
        shell: bash
        run: |
          mv php.exe bin
          curl https://curl.haxx.se/ca/cacert.pem --fail --location --output ./bin/cacert.pem
          yarn run build
          yarn run make

      - name: Delete PHP interpreter artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: php-windows

      - name: Code signing
        uses: azure/trusted-signing-action@v0.5.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://wus2.codesigning.azure.net/
          trusted-signing-account-name: da-trusted-signing-001
          certificate-profile-name: drupal-association-cert-profile
          files-folder: "./dist/win-unpacked"
          files-folder-filter: exe,dll
          files-folder-recurse: true
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: './dist/win-unpacked'
          overwrite: true
