name: Windows

on:
  push:
    branches:
      - main
      # PR branches that alter the build process should be prefixed with `build/`, so
      # that this workflow runs.
      - 'build/**'
  workflow_call:
  workflow_dispatch:

jobs:
  php:
    name: PHP
    uses: ./.github/workflows/php-windows.yml

  app:
    name: App
    runs-on: windows-latest
    needs:
      - php
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Set up Yarn
        run: |
          corepack enable
          yarn set version berry

# Dependency caching is temporarily disabled due to https://github.com/npm/cli/issues/4828.
#      - name: Cache dependencies
#        id: cache
#        uses: actions/cache@v4
#        with:
#          path: node_modules
#          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
#        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      # For reference -- this will extract the uploaded artifact (which is a ZIP file)
      # into a directory named after the artifact.
      - name: Download PHP interpreter
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ needs.php.outputs.artifact-id }}

      - name: Create bin directory
        run: mv php-windows bin

      - name: Extract Composer
        run: |
          cp $(which composer) composer.phar
          php.exe /c/tools/php/pharcommand.phar extract -f composer.phar ./composer
          rm composer.phar
        working-directory: bin
        shell: bash

      - name: Create application bundle
        run: |
          curl https://curl.haxx.se/ca/cacert.pem --fail --location --output cacert.pem
          yarn run build
          yarn run make
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete PHP interpreter artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: php-windows

      - name: Code signing
        uses: azure/trusted-signing-action@v0.5.1
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://wus2.codesigning.azure.net/
          trusted-signing-account-name: da-trusted-signing-001
          certificate-profile-name: drupal-association-cert-profile
          files-folder: "./dist/win-unpacked"
          files-folder-filter: exe,dll
          files-folder-recurse: true
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
