name: Launcher (Windows)

on:
  push:
    branches:
      - main
      # PR branches that alter the build process should be prefixed with `build/`, so
      # that this workflow runs.
      - 'build/**'
  workflow_call:
  workflow_dispatch:

jobs:
  php:
    name: Build PHP
    uses: ./.github/workflows/php-windows.yml

  build:
    name: Build launcher
    runs-on: windows-latest
    needs:
      - php
    steps:
      - uses: actions/checkout@v4

      - name: Download Composer
        uses: robinraju/release-downloader@v1
        with:
          repository: composer/composer
          latest: true
          fileName: composer.phar
          out-file-path: bin

      - name: Download PHP interpreter
        uses: actions/download-artifact@v4
        with:
          name: php-windows

      - name: Prepare binaries
        shell: bash
        run: mv php.exe bin

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm clean-install

      - name: Create application bundle
        run: npm run make

      - name: Delete PHP interpreter artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: php-windows

      - name: Code signing
        uses: azure/trusted-signing-action@v0.5.1
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: ${{ secrets.AZURE_ENDPOINT }}
          trusted-signing-account-name: ${{ secrets.AZURE_CODE_SIGNING_NAME }}
          certificate-profile-name: ${{ secrets.AZURE_CERT_PROFILE_NAME }}
          files-folder: "./out/Launch Drupal CMS-win32-x64"
          files-folder-filter: exe,dll
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: launcher-windows
          # @see forge.config.js.
          path: "./out/Launch Drupal CMS-win32-x64"
          overwrite: true
