name: Launcher (macOS)

on:
  push:
    branches:
      - main
      # PR branches that alter the build process should be prefixed with `build/`, so
      # that this workflow runs.
      - 'build/**'
  workflow_call:
  workflow_dispatch:

jobs:
  php:
    name: Build PHP
    uses: ./.github/workflows/php-macos.yml

  build:
    name: Build launcher
    strategy:
      matrix:
        runner:
          - macos-13  # x64
          - macos-14  # arm64
    runs-on: ${{ matrix.runner }}
    needs:
      - php
    steps:
      - uses: actions/checkout@v4

      # Set up the code signing certificate. This was copied from the example in
      # https://docs.github.com/en/actions/use-cases-and-examples/deploying/installing-an-apple-certificate-on-macos-runners-for-xcode-development.
      - name: Set up code signing
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Set up some useful variables.
          CERTIFICATE_PATH=$RUNNER_TEMP/build.p12
          PROVISION_PROFILE_PATH=$RUNNER_TEMP/build.provisionprofile
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Import the signing certificate and provisioning profile from our secrets.
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PROVISION_PROFILE_PATH

          # Create a temporary keychain which will hold the signing certificate.
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Add the certificate to the keychain.
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Apply the provisioning profile.
          # This path is based on what I found at https://stackoverflow.com/questions/45625347/xcode-provisioning-profiles-location#45642752
          mkdir -p ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles
          cp $PROVISION_PROFILE_PATH ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles

      - name: Download Composer
        uses: robinraju/release-downloader@v1
        with:
          repository: composer/composer
          latest: true
          fileName: composer.phar
          out-file-path: bin

      - name: Download PHP interpreter
        uses: actions/download-artifact@v4
        with:
          name: php-macos

      - name: Prepare binaries
        run: |
          chmod +x php
          mv php bin

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm clean-install

      - name: Create application bundle
        env:
          # @see forge.config.js
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: npm run make

      - name: Delete PHP interpreter artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: php-macos

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: launcher-${{ runner.arch }}
          path: './out/make/Launch Drupal CMS-*.dmg'
          # The DMG is already compressed.
          compression-level: 0
          overwrite: true
