name: Launcher (Windows)

on:
  push:
    branches:
      - main
      # PR branches that alter the build process should be prefixed with `build/`, so
      # that this workflow runs.
      - 'build/**'
  workflow_call:
  workflow_dispatch:

jobs:
  php:
    name: Build PHP
    uses: ./.github/workflows/php-windows.yml

  build:
    name: Build launcher
    runs-on: windows-latest
    needs:
      - php
    steps:
      - uses: actions/checkout@v4

      - name: Download Composer
        uses: robinraju/release-downloader@v1
        with:
          repository: composer/composer
          latest: true
          fileName: composer.phar
          out-file-path: bin

      - name: Download PHP interpreter
        uses: actions/download-artifact@v4
        with:
          name: php-windows

      - name: Prepare binaries
        shell: bash
        run: mv php.exe bin

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm clean-install

      - name: Create application bundle
        run: npm run make

      - name: Delete PHP interpreter artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: php-windows

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: launcher-windows
          # @see forge.config.js.
          path: "./out/Launch Drupal CMS-win32-x64"
          overwrite: true
