name: macOS

on:
  push:
    branches:
      - main
      # PR branches that alter the build process should be prefixed with `build/`, so
      # that this workflow runs.
      - 'build/**'
  workflow_call:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # The PHP interpreter needs to be its own job so it can be built for both x64 and arm64
  # architectures in parallel, before being merged into a universal binary while building
  # the app itself.
  php:
    name: Build PHP on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-13 # x64
          - macos-14 # arm64
    runs-on: ${{ matrix.os }}
    env:
      # The extensions and libraries needed to build PHP. These need to be variables so we can
      # use them to generate a cache key.
      # @see https://static-php.dev/en/guide/cli-generator.html
      PHP_EXTENSIONS: bz2,ctype,curl,dom,filter,gd,iconv,mbstring,opcache,openssl,pcntl,pdo,pdo_sqlite,phar,posix,session,simplexml,sodium,sqlite3,tokenizer,xml,xmlwriter,yaml,zip,zlib
      PHP_LIBRARIES: freetype,libavif,libjpeg,libwebp
      PHP_VERSION: 8.3
    steps:
      - uses: actions/checkout@v4
        with:
          repository: crazywhalecc/static-php-cli
          ref: 2.6.1

      - if: steps.cache.outputs.cache-hit != 'true'
        name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: pecl, composer
          extensions: curl, openssl, mbstring, tokenizer
          ini-values: memory_limit=-1

      # Cache the built binary so we can skip the build steps if there is a cache hit.
      - name: Generate cache key
        run: |
          CACHE_KEY=${{ runner.os }}-${{ runner.arch }}-$PHP_VERSION--$(echo $PHP_EXTENSIONS | tr ',' '-')
          echo "CACHE_KEY=${CACHE_KEY}" >> $GITHUB_ENV

      - id: cache
        name: Cache binaries
        uses: actions/cache@v4
        with:
          path: buildroot/bin
          key: php-${{ env.CACHE_KEY }}

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Install dependencies and build PHP
        run: |
          brew install automake gzip
          composer install --no-dev
          ./bin/spc doctor
          ./bin/spc download --with-php=${{ env.PHP_VERSION }} --for-extensions=${{ env.PHP_EXTENSIONS }} --prefer-pre-built
          ./bin/spc build ${{ env.PHP_EXTENSIONS }} --build-cli --with-libs="${{ env.PHP_LIBRARIES }}" --debug

      # Upload the built PHP interpreter.
      - uses: actions/upload-artifact@v4
        with:
          name: php-${{ runner.arch }}
          path: buildroot/bin
          retention-days: 1

  build:
    name: Build app
    runs-on: macos-latest
    needs:
      - php
    env:
      # Don't publish by default. This is overridden for the release branch, below.
      PUBLISH: never
    steps:
      - uses: actions/checkout@v4

      - name: Download PHP binary for arm64
        uses: actions/download-artifact@v4
        with:
          name: php-ARM64
          path: build/php-arm64

      - name: Download PHP binary for x64
        uses: actions/download-artifact@v4
        with:
          name: php-X64
          path: build/php-x64

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Set up Yarn
        run: |
          corepack enable
          yarn set version berry

# Dependency caching is temporarily disabled due to https://github.com/npm/cli/issues/4828.
#      - name: Cache dependencies
#        id: cache
#        uses: actions/cache@v4
#        with:
#          path: node_modules
#          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
#       if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      # This was copied from the example in
      # https://docs.github.com/en/actions/use-cases-and-examples/deploying/installing-an-apple-certificate-on-macos-runners-for-xcode-development.
      - name: Set up code signing
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Set up some useful variables.
          CERTIFICATE_PATH=$RUNNER_TEMP/build.p12
          PROVISION_PROFILE_PATH=$RUNNER_TEMP/build.provisionprofile
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Import the signing certificate and provisioning profile from our secrets.
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PROVISION_PROFILE_PATH

          # Create a temporary keychain which will hold the signing certificate.
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Add the certificate to the keychain.
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Apply the provisioning profile.
          # This path is based on what I found at https://stackoverflow.com/questions/45625347/xcode-provisioning-profiles-location#45642752
          mkdir -p ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles
          cp $PROVISION_PROFILE_PATH ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles

      - name: Enable notarization and publishing for the release branch
        if: github.ref_name == 'main'
        run: |
          # Set environment variables so Electron Builder will notarize in the next step.
          echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> $GITHUB_ENV
          echo "APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" >> $GITHUB_ENV
          echo "APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}" >> $GITHUB_ENV
          echo "PUBLISH=onTagOrDraft" >> $GITHUB_ENV

      - name: Create universal PHP binary, extract Composer, and make application
        run: |
          lipo -create ./build/php-x64/php ./build/php-arm64/php -output ./bin/php
          cp $(which composer) composer.phar
          phar extract -f composer.phar ./bin/composer
          rm composer.phar
          chmod +x ./bin/php
          curl https://curl.haxx.se/ca/cacert.pem --fail --location --output cacert.pem
          yarn run build
          npx electron-builder --universal --publish=${{ env.PUBLISH }}

      - name: Upload distributable
        if: ${{ env.PUBLISH == 'never' }}
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: dist/*.dmg
          retention-days: 7
