name: Release

on:
  push:
    tags:
      - '*'

jobs:
  app-macos:
    name: Build for macOS
    uses: ./.github/workflows/app-macos.yml
    secrets: inherit

  app-windows:
    name: Build for Windows
    uses: ./.github/workflows/app-windows.yml
    secrets: inherit

  app-linux:
    name: Build for Linux
    uses: ./.github/workflows/app-linux.yml
    secrets: inherit

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - app-macos
      - app-windows
      - app-linux
    steps:
      - name: Download app for macOS (arm64)
        uses: actions/download-artifact@v4
        with:
          name: app-mac-ARM64
          path: mac-arm64

      - name: Download app for macOS (x64)
        uses: actions/download-artifact@v4
        with:
          name: app-mac-X64
          path: mac-x64

      - name: Download app for Windows
        uses: actions/download-artifact@v4
        with:
          name: app-windows
          path: "Drupal CMS"

      - name: Download app for Linux (arm64)
        uses: actions/download-artifact@v4
        with:
          name: app-linux-ARM64
          path: linux-arm64

      - name: Download app for Linux (x64)
        uses: actions/download-artifact@v4
        with:
          name: app-linux-X64
          path: linux-x64

      - name: Gather assets
        run: |
          mv "./mac-arm64/Launch Drupal CMS.dmg" "Drupal CMS for macOS (Apple silicon).dmg"
          mv "./mac-x64/Launch Drupal CMS.dmg" "Drupal CMS for macOS (Intel).dmg"
          zip -q -r "Drupal CMS (Windows).zip" "Drupal CMS"
          mv "./linux-arm64/Launch Drupal CMS.AppImage" "Drupal CMS for Linux (arm64).AppImage"
          mv "./linux-x64/Launch Drupal CMS.AppImage" "Drupal CMS for Linux (x64).AppImage"

      - name: Delete arm64 macOS app artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app-mac-ARM64

      - name: Delete x64 macOS app artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app-mac-X64

      - name: Delete Windows app artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app-windows

      - name: Delete arm64 Linux app artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app-linux-ARM64

      - name: Delete x64 Linux app artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app-linux-X64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Drupal CMS for macOS (Apple silicon).dmg
            Drupal CMS for macOS (Intel).dmg
            Drupal CMS (Windows).zip
            Drupal CMS for Linux (arm64).AppImage
            Drupal CMS for Linux (x64).AppImage
