name: Release

on:
  push:
    tags:
      - '*'

jobs:
  launcher-macos:
    name: Build launcher for macOS
    uses: ./.github/workflows/launcher-macos.yml

  launcher-windows:
    name: Build launcher for Windows
    uses: ./.github/workflows/launcher-windows.yml

  publish:
    name: Release assets
    runs-on: ubuntu-latest
    needs:
      - launcher-macos
      - launcher-windows
    steps:
      - name: Download launcher for macOS (arm64)
        uses: actions/download-artifact@v4
        with:
          name: drupal-cms-ARM64
          path: arm64

      - name: Download launcher for macOS (x64)
        uses: actions/download-artifact@v4
        with:
          name: drupal-cms-X64
          path: x64

      - name: Download launcher for Windows
        uses: actions/download-artifact@v4
        with:
          name: drupal-cms-windows
          path: "Drupal CMS"

      - name: Gather assets
        run: |
          mv "./arm64/Launch Drupal CMS-1.0.0-arm64.dmg" "Drupal CMS (macOS Apple Silicon).dmg"
          mv "./x64/Launch Drupal CMS-1.0.0-x64.dmg" "Drupal CMS (macOS Intel).dmg"
          zip -q -r "Drupal CMS (Windows).zip" "Drupal CMS"

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Drupal CMS (macOS Apple Silicon).dmg
            Drupal CMS (macOS Intel).dmg
            Drupal CMS (Windows).zip
