name: Release

on:
  push:
    tags:
      - '*'

jobs:
  app-macos:
    name: Build app for macOS
    uses: ./.github/workflows/app-macos.yml
    secrets: inherit

  app-windows:
    name: Build app for Windows
    uses: ./.github/workflows/app-windows.yml
    secrets: inherit

  publish:
    name: Release assets
    runs-on: ubuntu-latest
    needs:
      - app-macos
      - app-windows
    steps:
      - name: Download app for macOS (arm64)
        uses: actions/download-artifact@v4
        with:
          name: app-ARM64
          path: mac-arm64

      - name: Download app for macOS (x64)
        uses: actions/download-artifact@v4
        with:
          name: app-X64
          path: mac-x64

      - name: Download app for Windows
        uses: actions/download-artifact@v4
        with:
          name: app-windows
          path: win

      - name: Gather assets
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          mv "./mac-arm64/Launch Drupal CMS-$VERSION-arm64.dmg" "Drupal CMS (macOS Apple silicon).dmg"
          mv "./mac-x64/Launch Drupal CMS-$VERSION-x64.dmg" "Drupal CMS (macOS Intel).dmg"
          mv "./win/Launch Drupal CMS-$VERSION.exe" "Drupal CMS.exe"

      - name: Delete arm64 macOS app artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app-ARM64

      - name: Delete x64 macOS app artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app-X64

      - name: Delete Windows app artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app-windows

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Drupal CMS (macOS Apple silicon).dmg
            Drupal CMS (macOS Intel).dmg
            Drupal CMS.exe
