name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run this workflow at 9 AM UTC every day.
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          # Testing on Linux is temporarily disabled until we can figure out the SUID sandboxing issue.
          # - ubuntu-latest
          # Testing on Windows is temporarily disabled because it's broken.
          # - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: composer
          ini-values: memory_limit=-1

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run tests
        run: |
          composer run assets --working-dir=build
          npm run test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ runner.os }}
          path: playwright-report/
          retention-days: 7
