name: Windows

on:
  push:
    branches:
      - main
      # PR branches that alter the build process should be prefixed with `build/`, so
      # that this workflow runs.
      - 'build/**'
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PHP_EXTENSIONS: bz2,ctype,curl,dom,filter,gd,iconv,mbstring,opcache,openssl,pdo,pdo_sqlite,phar,session,simplexml,sqlite3,tokenizer,xml,xmlwriter,yaml,zip,zlib
      PHP_LIBRARIES: libjpeg,libavif,freetype,libwebp
      PHP_VERSION: 8.3
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer

      - name: Generate cache key
        shell: bash
        run: |
          CACHE_KEY=${{ runner.os }}-$PHP_VERSION-$(echo $PHP_EXTENSIONS | tr ',' '-')
          echo "CACHE_KEY=${CACHE_KEY}" >> "$GITHUB_ENV"

      # Cache the built PHP interpreter.
      - id: cache-php
        name: Cache binaries
        uses: actions/cache@v4
        with:
          path: build/buildroot/bin
          key: php-${{ env.CACHE_KEY }}

      - if: steps.cache-php.outputs.cache-hit != 'true'
        name: Build PHP interpreter
        run: |
          composer require crazywhalecc/static-php-cli:dev-main
          composer exec spc doctor
          composer exec spc download --with-php="${{ env.PHP_VERSION }}" --for-extensions="${{ env.PHP_EXTENSIONS }}" --prefer-pre-built
          composer exec spc build "${{ env.PHP_EXTENSIONS }}" --build-cli --with-libs="${{ env.PHP_LIBRARIES }}" --debug
        working-directory: build
